### ISSUE TITLE
Personal »About« links resulting in 404

### ISSUE THREAD

**Issue by unseen-ninja** [centauri-hacks/website#6]
All personal links within the about section result in a 404 due to people within the org not being visible to the public. Generally it might be beneficial to just link to their Github profiles themselves as the org overview just shows access to repos etc. As this is about the people behind the project their personal profile might be more relevant.

**Comment by BlueFalconHD** [comment]
Hello, friend! Thanks for checking this out and providing feedback! That was my mistake, as I just copied the links from the member list absentmindedly! Thanks.

**Comment by BlueFalconHD** [comment]
@andreasgrafen fixed :)
